# Generated by Django 2.2.1 on 2019-11-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20191116_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='salario',
        ),
    ]
