# Generated by Django 3.0 on 2020-03-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='produto',
            field=models.ManyToManyField(to='produto.Produto'),
        ),
    ]
