# Generated by Django 3.0 on 2020-03-11 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_auto_20200216_1457'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='contrato',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contrato.Contrato'),
            preserve_default=False,
        ),
    ]
