# Generated by Django 3.0 on 2020-03-11 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_auto_20200216_1457'),
        ('produto', '0002_produto_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='contrato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.Contrato'),
        ),
    ]
